version: '2'

services:
  mpu9250:
    image: openkorp/openkorp-device-mpu9250-multi:latest
    network_mode: host
    devices:
      - /dev/i2c-2:/dev/i2c-2
    command: "openkorp-device-mpu9250 --cid=111 --freq=1 --dev=/dev/i2c-2 --id=0 --verbose=1"